sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t chloe101/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chloe101/docker-react npm run test