sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t chloe101/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chloe101/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-653777625255"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

